# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 17:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutonomousSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_number', models.BigIntegerField(unique=True, verbose_name='AS Number')),
                ('fqdn', models.CharField(max_length=255, verbose_name='FQDN')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Autonomous System',
                'verbose_name_plural': 'Autonomous Systems',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Code')),
                ('owners', models.ManyToManyField(related_name='institutions', to=settings.AUTH_USER_MODEL, verbose_name='Managers')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
        migrations.CreateModel(
            name='IPv4Subnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='Network Address')),
                ('subnet_bits', models.IntegerField(verbose_name='Subnet Bits')),
                ('dns_server', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='DNS Server')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipv4_subnets', to='lana_data.Institution', verbose_name='Institution')),
            ],
            options={
                'verbose_name': 'IPv4 Subnet',
                'verbose_name_plural': 'IPv4 Subnets',
            },
        ),
        migrations.AddField(
            model_name='autonomoussystem',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autonomous_systems', to='lana_data.Institution', verbose_name='Institution'),
        ),
        migrations.AlterUniqueTogether(
            name='ipv4subnet',
            unique_together=set([('network_address', 'subnet_bits')]),
        ),
    ]
