# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lana_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
