# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lana_data', '0002_tunnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='autonomoussystem',
            name='location_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='autonomoussystem',
            name='location_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
