# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lana_data', '0002_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnelendpoint',
            name='external_hostname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='External hostname'),
        ),
    ]
