# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lana_data', '0003_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='autonomoussystem',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='ipv4subnet',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='tunnel',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
    ]
