# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lana_data', '0003_as_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='abuse_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Abuse Email'),
        ),
    ]
