# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lana_data', '0003_auto_20160428_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autonomoussystem',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='ipv4subnet',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='ipv4subnet',
            name='dns_server',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='DNS Server'),
        ),
    ]
