# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lana_data', '0004_auto_20160429_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autonomoussystem',
            name='as_number',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='AS Number'),
        ),
    ]
