# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 01:45
from __future__ import unicode_literals

from django.db import migrations
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lana_data', '0005_subnet_network_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipv4subnet',
            name='dns_server',
            field=netfields.fields.InetAddressField(blank=True, max_length=39, null=True, verbose_name='DNS Server'),
        ),
        migrations.AlterField(
            model_name='tunnelendpoint',
            name='external_ipv4',
            field=netfields.fields.InetAddressField(blank=True, max_length=39, null=True, verbose_name='External IPv4 address'),
        ),
        migrations.AlterField(
            model_name='tunnelendpoint',
            name='internal_ipv4',
            field=netfields.fields.InetAddressField(blank=True, max_length=39, null=True, verbose_name='Internal IPv4 address'),
        ),
    ]
