# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lana_data', '0005_fastdtunnelendpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastdtunnelendpoint',
            name='port',
            field=models.IntegerField(blank=True, help_text='Defaults to remote AS number if ≤ 65535.', null=True, verbose_name='Port'),
        ),
    ]
