# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lana_data', '0006_netfields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autonomoussystem',
            options={'ordering': ['as_number'], 'verbose_name': 'Autonomous System', 'verbose_name_plural': 'Autonomous Systems'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['code'], 'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
        migrations.AlterModelOptions(
            name='ipv4subnet',
            options={'ordering': ['network'], 'verbose_name': 'IPv4 Subnet', 'verbose_name_plural': 'IPv4 Subnets'},
        ),
        migrations.AlterModelOptions(
            name='tunnel',
            options={'ordering': ['endpoint1__autonomous_system__as_number', 'endpoint2__autonomous_system__as_number']},
        ),
    ]
