# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 22:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lana_data', '0006_host_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='as_range',
            field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(blank=True, null=True, verbose_name='AS Range'),
        ),
    ]
