# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lana_data', '0006_fastd_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='VtunTunnel',
            fields=[
                ('tunnel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lana_data.Tunnel')),
                ('transport', models.CharField(choices=[('udp', 'udp'), ('tcp', 'tcp')], max_length=3, verbose_name='Transport protocol')),
                ('compression', models.CharField(blank=True, max_length=255, null=True, verbose_name='Compression')),
            ],
            bases=('lana_data.tunnel',),
        ),
        migrations.CreateModel(
            name='VtunTunnelEndpoint',
            fields=[
                ('tunnelendpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lana_data.TunnelEndpoint')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='Port')),
            ],
            bases=('lana_data.tunnelendpoint',),
        ),
    ]
