# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-13 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lana_data', '0006_dynamic_ipv4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bfd_enabled', models.BooleanField(default=False, verbose_name='BFD enabled')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
            ],
            options={
                'verbose_name': 'Peering',
                'ordering': ['tunnelpeering__tunnel__endpoint1__host__autonomous_system__as_number', 'tunnelpeering__tunnel__endpoint2__host__autonomous_system__as_number'],
                'verbose_name_plural': 'Peerings',
            },
        ),
        migrations.CreateModel(
            name='TunnelPeering',
            fields=[
                ('peering_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lana_data.Peering')),
                ('tunnel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peering', to='lana_data.Tunnel', verbose_name='Tunnel')),
            ],
            options={
                'verbose_name': 'Tunnel Peering',
                'ordering': ['tunnel__endpoint1__host__autonomous_system__as_number', 'tunnel__endpoint2__host__autonomous_system__as_number'],
                'verbose_name_plural': 'Tunnel Peerings',
            },
            bases=('lana_data.peering',),
        ),
    ]
