# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-07 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lana_data', '0007_peering'),
    ]

    operations = [
        migrations.CreateModel(
            name='WireGuardTunnel',
            fields=[
                ('tunnel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lana_data.Tunnel')),
            ],
            bases=('lana_data.tunnel',),
        ),
        migrations.CreateModel(
            name='WireGuardTunnelEndpoint',
            fields=[
                ('tunnelendpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lana_data.TunnelEndpoint')),
                ('port', models.IntegerField(blank=True, help_text='Defaults to remote AS number if ≤ 65535.', null=True, verbose_name='Port')),
                ('public_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Public key')),
            ],
            bases=('lana_data.tunnelendpoint',),
        ),
    ]
