# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-19 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lana_data', '0008_wireguard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='autonomous_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='lana_data.AutonomousSystem', verbose_name='Autonomous System'),
        ),
        migrations.AlterField(
            model_name='tunnelendpoint',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tunnel_endpoints', to='lana_data.Host', verbose_name='Host'),
        ),
    ]
