# Generated by Django 2.0.13 on 2020-04-19 20:57

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lana_data', '0009_deprecation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='color',
            field=colorfield.fields.ColorField(default='#808080', max_length=18, verbose_name='Institution Color'),
        ),
    ]
