# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contact_information', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Contact Information')),
                ('show_email', models.BooleanField(default=False, verbose_name='Show email')),
                ('skype_user', models.CharField(blank=True, max_length=64, verbose_name='Skype User')),
                ('xmpp_address', models.CharField(blank=True, max_length=255, verbose_name='XMPP address')),
                ('additional_text', models.TextField(blank=True, verbose_name='Additional Text')),
            ],
            options={
                'verbose_name_plural': 'Contact Information',
                'verbose_name': 'Contact Information',
            },
        ),
    ]
