# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import lana_dashboard.usermanagement.validators


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='pgp_key',
            field=models.TextField(blank=True, validators=[lana_dashboard.usermanagement.validators.validate_pgp_key], verbose_name='PGP Key'),
        ),
    ]
